---
title: "fst ngsParalog filtering"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load relevant libraries and data
```{r}
library(tidyverse)
```


```{r}
# table for chromosome name and number
# two columns: chr (numbered) and chrName (what your chromosomes are called in your angsd output file)
chrom_df <- read.table("/fs/cbsubscb16/storage/rkc/sample_lists/chrom_meta_data.txt", header = TRUE, col.names = c("chrName","chrNewName")) %>% mutate(chr = seq(1,104,1)) %>% dplyr::select(-chrNewName)

# read in position files
AI_wgph_pos <- read_delim("/fs/cbsubscb16/storage/rkc/angsd/counts/PCAM-PPLA_AI_wgph.pos") %>% dplyr::rename(chrName = chr) %>% left_join(chrom_df, by = "chrName", ) %>%
    subset(select = -c(chrName))
EBS_wgph_pos <- read_delim("/fs/cbsubscb16/storage/rkc/angsd/counts/PCAM-PPLA_EBS_wgph.pos") %>% dplyr::rename(chrName = chr) %>% left_join(chrom_df, by = "chrName", ) %>%
    subset(select = -c(chrName))
GOA_wgph_pos <- read_delim("/fs/cbsubscb16/storage/rkc/angsd/counts/PCAM-PPLA_GOA_wgph.pos") %>% dplyr::rename(chrName = chr) %>% left_join(chrom_df, by = "chrName", ) %>%
    subset(select = -c(chrName))
NBS_wgph_pos <- read_delim("/fs/cbsubscb16/storage/rkc/angsd/counts/PCAM-PPLA_NBS_wgph.pos") %>% dplyr::rename(chrName = chr) %>% left_join(chrom_df, by = "chrName", ) %>%
    subset(select = -c(chrName))
SEAK_wgph_pos <- read_delim("/fs/cbsubscb16/storage/rkc/angsd/counts/PCAM-PPLA_SEAK_wgph.pos") %>% dplyr::rename(chrName = chr) %>% left_join(chrom_df, by = "chrName", ) %>%
    subset(select = -c(chrName))
```

```{r}
AI_EBS_fst <- read_tsv("/fs/cbsubscb16/storage/rkc/angsd/fst/AI-EastBering.fst.txt", col_names = c("region", "chrName", "pos", "Nsites","fst"), skip = 1) %>%  mutate(correct_fst = ifelse(fst < 0, 0, fst)) %>%  
  left_join(chrom_df, by = "chrName") %>%
    subset(select = -c(chrName)) %>%
    dplyr::select(chr, pos, correct_fst)

AI_GOA_fst <- read_tsv("/fs/cbsubscb16/storage/rkc/angsd/fst/AI-GOA.fst.txt", col_names = c("region", "chrName", "pos", "Nsites","fst"), skip = 1) %>%  mutate(correct_fst = ifelse(fst < 0, 0, fst)) %>%  
  left_join(chrom_df, by = "chrName") %>%
    subset(select = -c(chrName)) %>%
    dplyr::select(chr, pos, correct_fst)

NBS_AI_fst <- read_tsv("/fs/cbsubscb16/storage/rkc/angsd/fst/AI-NorthBering.fst.txt", col_names = c("region", "chrName", "pos", "Nsites","fst"), skip = 1) %>%  mutate(correct_fst = ifelse(fst < 0, 0, fst)) %>%  
  left_join(chrom_df, by = "chrName") %>%
    subset(select = -c(chrName)) %>%
    dplyr::select(chr, pos, correct_fst)

AI_SEAK_fst <- read_tsv("/fs/cbsubscb16/storage/rkc/angsd/fst/AI-SEAK.fst.txt", col_names = c("region", "chrName", "pos", "Nsites","fst"), skip = 1) %>%  mutate(correct_fst = ifelse(fst < 0, 0, fst)) %>%  
  left_join(chrom_df, by = "chrName") %>%
    subset(select = -c(chrName)) %>%
    dplyr::select(chr, pos, correct_fst)

EBS_GOA_fst <- read_tsv("/fs/cbsubscb16/storage/rkc/angsd/fst/EastBering-GOA.fst.txt", col_names = c("region", "chrName", "pos", "Nsites","fst"), skip = 1) %>%  mutate(correct_fst = ifelse(fst < 0, 0, fst)) %>%  
  left_join(chrom_df, by = "chrName") %>%
    subset(select = -c(chrName)) %>%
    dplyr::select(chr, pos, correct_fst)

NBS_EBS_fst <- read_tsv("/fs/cbsubscb16/storage/rkc/angsd/fst/EastBering-NorthBering.fst.txt", col_names = c("region", "chrName", "pos", "Nsites","fst"), skip = 1) %>%  mutate(correct_fst = ifelse(fst < 0, 0, fst)) %>%  
  left_join(chrom_df, by = "chrName") %>%
    subset(select = -c(chrName)) %>%
    dplyr::select(chr, pos, correct_fst)

EBS_SEAK_fst <- read_tsv("/fs/cbsubscb16/storage/rkc/angsd/fst/EastBering-SEAK.fst.txt", col_names = c("region", "chrName", "pos", "Nsites","fst"), skip = 1) %>%  mutate(correct_fst = ifelse(fst < 0, 0, fst)) %>%  
  left_join(chrom_df, by = "chrName") %>%
    subset(select = -c(chrName)) %>%
    dplyr::select(chr, pos, correct_fst)

NBS_GOA_fst <- read_tsv("/fs/cbsubscb16/storage/rkc/angsd/fst/GOA-NorthBering.fst.txt", col_names = c("region", "chrName", "pos", "Nsites","fst"), skip = 1) %>%  mutate(correct_fst = ifelse(fst < 0, 0, fst)) %>%  
  left_join(chrom_df, by = "chrName") %>%
    subset(select = -c(chrName)) %>%
    dplyr::select(chr, pos, correct_fst)

GOA_SEAK_fst <- read_tsv("/fs/cbsubscb16/storage/rkc/angsd/fst/GOA-SEAK.fst.txt", col_names = c("region", "chrName", "pos", "Nsites","fst"), skip = 1) %>%  mutate(correct_fst = ifelse(fst < 0, 0, fst)) %>%  
  left_join(chrom_df, by = "chrName") %>%
    subset(select = -c(chrName)) %>%
    dplyr::select(chr, pos, correct_fst)

NBS_SEAK_fst <- read_tsv("/fs/cbsubscb16/storage/rkc/angsd/fst/NorthBering-SEAK.fst.txt", col_names = c("region", "chrName", "pos", "Nsites","fst"), skip = 1) %>%  mutate(correct_fst = ifelse(fst < 0, 0, fst)) %>%  
  left_join(chrom_df, by = "chrName") %>%
    subset(select = -c(chrName)) %>%
    dplyr::select(chr, pos, correct_fst)
```

#### Test script for filtering fst files
```{r}
AI_EBS_wgph_fst <- AI_EBS_fst %>% inner_join(AI_wgph_pos, by = c("chr" = "chr", "pos" = "pos")) %>% inner_join(EBS_wgph_pos, by = c("chr" = "chr", "pos" = "pos")) %>% dplyr::select(c(-totDepth.x,-totDepth.y))
write_tsv(AI_EBS_wgph_fst, "/fs/cbsubscb16/storage/rkc/angsd/fst/AI-EBS_wgph.fst.txt")

AI_GOA_wgph_fst <- AI_GOA_fst %>% inner_join(AI_wgph_pos, by = c("chr" = "chr", "pos" = "pos")) %>% inner_join(GOA_wgph_pos, by = c("chr" = "chr", "pos" = "pos")) %>% dplyr::select(c(-totDepth.x,-totDepth.y))
write_tsv(AI_GOA_wgph_fst, "/fs/cbsubscb16/storage/rkc/angsd/fst/AI-GOA_wgph.fst.txt")

NBS_AI_wgph_fst <- NBS_AI_fst %>% inner_join(AI_wgph_pos, by = c("chr" = "chr", "pos" = "pos")) %>% inner_join(NBS_wgph_pos, by = c("chr" = "chr", "pos" = "pos")) %>% dplyr::select(c(-totDepth.x,-totDepth.y))
write_tsv(NBS_AI_wgph_fst, "/fs/cbsubscb16/storage/rkc/angsd/fst/AI-NBS_wgph.fst.txt")

AI_SEAK_wgph_fst <- AI_SEAK_fst %>% inner_join(AI_wgph_pos, by = c("chr" = "chr", "pos" = "pos")) %>% inner_join(SEAK_wgph_pos, by = c("chr" = "chr", "pos" = "pos")) %>% dplyr::select(c(-totDepth.x,-totDepth.y))
write_tsv(AI_SEAK_wgph_fst, "/fs/cbsubscb16/storage/rkc/angsd/fst/AI-SEAK_wgph.fst.txt")

EBS_GOA_wgph_fst <- EBS_GOA_fst %>% inner_join(EBS_wgph_pos, by = c("chr" = "chr", "pos" = "pos")) %>% inner_join(GOA_wgph_pos, by = c("chr" = "chr", "pos" = "pos")) %>% dplyr::select(c(-totDepth.x,-totDepth.y))
write_tsv(EBS_GOA_wgph_fst, "/fs/cbsubscb16/storage/rkc/angsd/fst/EBS-GOA_wgph.fst.txt")

NBS_EBS_wgph_fst <- NBS_EBS_fst %>% inner_join(EBS_wgph_pos, by = c("chr" = "chr", "pos" = "pos")) %>% inner_join(NBS_wgph_pos, by = c("chr" = "chr", "pos" = "pos")) %>% dplyr::select(c(-totDepth.x,-totDepth.y))
write_tsv(NBS_EBS_wgph_fst, "/fs/cbsubscb16/storage/rkc/angsd/fst/EBS-NBS_wgph.fst.txt")

EBS_SEAK_wgph_fst <- EBS_SEAK_fst %>% inner_join(EBS_wgph_pos, by = c("chr" = "chr", "pos" = "pos")) %>% inner_join(SEAK_wgph_pos, by = c("chr" = "chr", "pos" = "pos")) %>% dplyr::select(c(-totDepth.x,-totDepth.y))
write_tsv(EBS_SEAK_wgph_fst, "/fs/cbsubscb16/storage/rkc/angsd/fst/EBS-SEAK_wgph.fst.txt")

NBS_GOA_wgph_fst <- NBS_GOA_fst %>% inner_join(GOA_wgph_pos, by = c("chr" = "chr", "pos" = "pos")) %>% inner_join(NBS_wgph_pos, by = c("chr" = "chr", "pos" = "pos")) %>% dplyr::select(c(-totDepth.x,-totDepth.y))
write_tsv(NBS_GOA_wgph_fst, "/fs/cbsubscb16/storage/rkc/angsd/fst/GOA-NBS_wgph.fst.txt")

GOA_SEAK_wgph_fst <- GOA_SEAK_fst %>% inner_join(GOA_wgph_pos, by = c("chr" = "chr", "pos" = "pos")) %>% inner_join(SEAK_wgph_pos, by = c("chr" = "chr", "pos" = "pos")) %>% dplyr::select(c(-totDepth.x,-totDepth.y))
write_tsv(GOA_SEAK_wgph_fst, "/fs/cbsubscb16/storage/rkc/angsd/fst/GOA-SEAK_wgph.fst.txt")

NBS_SEAK_wgph_fst <- NBS_SEAK_fst %>% inner_join(NBS_wgph_pos, by = c("chr" = "chr", "pos" = "pos")) %>% inner_join(SEAK_wgph_pos, by = c("chr" = "chr", "pos" = "pos")) %>% dplyr::select(c(-totDepth.x,-totDepth.y))
write_tsv(NBS_SEAK_wgph_fst, "/fs/cbsubscb16/storage/rkc/angsd/fst/NBS-SEAK_wgph.fst.txt")
```

